[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.14"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "go.uber.org/atomic"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
